#####i3status Configuration File:(Depdencies: i3status)
###Genearl Configuration:
general {
    colors = true
    interval = 5
}

###Sensors & Order:
#order += "cpu_temperature 0"
order += "cpu_usage"
order += "load"
order += "memory"
order += "disk /"
order += "ethernet"
order += "volume master"
order += "time"

###Sensor Configurations:
##CPU_Temperature:
cpu_temperature 0 {
        format = "Temp: %degrees °C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input"
}

##CPU_Usage:
cpu_usage {
    format = "%usage"
}

##CPU_Load:
load {
    format = "%1min"
}

##Memory:
memory {
       format = "%used / %total"
}

##disk "/":
disk "/" {
    format = "%free"
	low_threshold = "20"
	format_below_threshold = "Warning: Less than %free remaining"
}

##Ethernet:
ethernet enp4s0 {
         format_up = "E: %ip"
         format_down = "E: %ip"
}

##Volume Master:
volume master {
    format = "♪: %volume"
    format_muted = "♪: muted (%volume)"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

##Time:
time {
    #format = "%d.%m.%Y %H:%M"
    format = "%H:%M"
}
