filesize_format = "B" # can be b, kb, kib, mb, mib, gb, gib, etc
filesize_metric = true # true => (KB, MB, GB), false => (KiB, MiB, GiB)
skip_welcome_message = false # Note to nushell developer: This is expected to be false, when testing nushell itself
disable_table_indexes = false
nonzero_exit_errors = true
startup = [
    "alias la = ls --long",
##ALIASES
##Arch:
#pacman:
    "alias pac = sudo pacman -Syu",            	    #Update standard package(s)
    "alias pacit = sudo pacman -S",          	    #Unstall package(s)
    "alias pacrem = sudo pacman -R",           	    #Remove package(s)
    "alias pacremall = sudo pacman -Rncs",		    #Remove package(s) and all dependencies
    "alias pacseach = sudo pacman -Q",         	    #Search for package(s)
#yay:
    "alias yaysua = sudo yay -Sua",            	    #Updates only AUR package(s)
    "alias yayrem = sudo yay -R",              	    #Remove package(s)
    "alias yaysearch = sudo yay -Q",           	    #Search for package(s)
#paru:
    "alias parusua = sudo paru -Sua",          	    #Updates only AUR package(s)
    "alias parurem = sudo paru -R",            	    #Remove package(s)
    "alias parusearch = sudo paru -Q",         	    #Search for package(s)

##Debian:
#apt & apt-get
    #"alias up = sudo apt-get update",			        #Downloads updates
    #"alias upg = sudo apt-get upgrade",		        #Applies updates to system
    #"alias it = sudo apt install",			        #Install package(s)
    #"alias rem = sudo apt remove",			        #Remove package(s)
    #"alias atrm = sudo apt autoremove",		        #Autoremove orphaned package(s) & dependencies

##Solus:
#eopkg:
    #"alias upg = sudo eopkg upgrade",                 #Download and apply update(s)
    #"alias it = sudo eopkg install",                  #Install package(s)
    #"alias rem = sudo eopkg remove",                  #Remove package(s)
    #"alias atrm = sudo eopkg autoremove",             #Autoremove orphaned package(s) & dependencies
    #"alias listup = sudo eopkg list-upgrades",        #List available upgrade(s) for package(s)
    #"alias esearch = sudo eopkg search",              #Search for package(s)

##Fedora/RHEL:
#dnf:
    #"alias upg = sudo dnf upgrade",                   #Download and apply update(s)
    #"alias dit = sudo dnf install",                   #Install package(s)
    #"alias drem = sudo dnf remove",                   #Remove package(s)
    #"alias atrm = sudo dnf autoremove",               #Autoremove orphaned package(s) & dependencies

##BSD:
#pkg:
    #"alias bsdup = sudo freebsd-update fetch",        #Download system updates
    #"alias bsdupg = sudo freebsd-update install",     #Install updates to system
    #"alias upg = sudo pkg upgrade",                   #Download and apply updates for package(s)
    #"alias pkgit = sudo pkg install",                 #Install package(s)
    #"alias pkgrem = sudo pkg remove",                 #Remove package(s)
    #"alias atrm = sudo pkg autoremove",               #Autoremove orphaned package(s) & dependencies
    #"alias pkglock = sudo pkg lock",                  #Lock package(s) from being removed or edited
    #"alias pkgulock = sudo pkg unlock",               #Unlock package(s)
    #"alias audit = sudo pkg audit",                   #Audit package(s) for vulnerabilities and bugs
    #"alias auditall = sudo pkg audit -F",             #Audit all packages for vulnerabilities and bugs
    #"alias chshb = chsh -s /usr/local/bin/bash",      #Changes user shell to 'bash' shell (reboot required)
    #"alias chshf = chsh -s /usr/local/bin/fish",      #Changes user shell to 'fish' shell (reboot required)
    #"alias chshz = chsh -s /usr/local/bin/zsh",       #Changes user shell to 'zsh' shell (reboot required)

##Navigation:
    "alias .. = cd ..",				                  #Go up one directory
    "alias .2 = cd ../..",				              #Go up two directories
    "alias .3 = cd ../../..",                         #Go up three directories

##Surfshark-VPN Aliases:
    "alias vpnup = sudo surfshark-vpn attack",        #Quick connect to nearest server
    "alias vpnmulti = sudo surfshark-vpn multi",      #Connects to multi-hop server
    "alias vpndown = sudo surfshark-vpn down",        #Disconnects vpn
    "alias vpnstat = sudo surfshark-vpn status",      #Show vpn status
    "alias vpnver = sudo surfshark-vpn version",      #Show surfshark-vpn version

##'liquidctl' Aliases (Corsair Commander Pro):
    "alias liqlist = sudo liquidctl list",			            #List available devices
    "alias liqstart = sudo liquidctl initialize",		        #Initialize all available device(s)
    "alias liqstart = sudo liquidctl status",			        #Show status of available device(s)
    "alias fan1start = sudo liquidctl set fan1 speed 60",	    #Set fan1 to 60% speed
    "alias fan2start = sudo liquidctl set fan2 speed 60",	    #Set fan2 to 60% speed
    "alias fan3start = sudo liquidctl set fan3 speed 60",	    #Set fan3 to 60% speed

##Timeshift (BTRFS) Aliases
    #"alias timelistsnap = sudo timeshift --list-snapshots",    #List snapshots
    #"alias timelistdev = sudo timeshift --list-devices",       #List devices
    #"alias timecheck = sudo timeshfit --check",                #Create snapshot if scheduled
    #"alias timesnap = sudo timeshift --create",                #Create snapshot
    #"alias snapcomment = sudo timeshift --comments",           #Set snapshot description
    #"alias timerestore = sudo timeshift --restore",            #Restore from snapshot

##General Aliases:
    "alias c = clear",				                #clear screen
    "alias h = history",				                #Show command history
    "alias nft = neofetch",                           #Neofetch

##Command Swaps:
#'ls' to 'exa':
    "alias ls = exa -al --color=always",		        #Ls listing all in list format
    "alias la = exa -a --color=always",		        #Ls listing all
    "alias ll = exa -l --color=always",		        #Ls list format
    "alias lt = exa -aT --color-always",              #Show all contents in tree format
#'cat' to 'bat':
    "alias cat = bat",                                #Use bat instead of cat

##General System Tools:
    "alias cp = cp -i",				                #Confirm before overwriting existing file
    "alias mv = mv -i",				                #Confirm before overwriting existing file
    "alias rm = rm -i",				                #Confirm before removing file
    "alias df = df -h",				                #List drive space in human readable format
    "alias free = free -m",				            #Show sizes in MB

##Power Commands:
#Linux:
    "alias shutdown = sudo shutdown now",		        #Shutdown system
    "alias reboot = sudo reboot",			            #Reboot system
#BSD:
    #"alias shutdown = sudo poweroff",                 #Shutdown system
    #"alias reboot = sudo init 6",                     #Reboot system

##Text Editor & Config File Aliases:
#VIM ALIASES:
    "alias v = vim",                                  #Shortcut for vim command
    "alias vbash = vim ~/.bashrc",                    #Open bash config in vim
    "alias vfish = vim ~/.config/fish/config.fish",   #Open fish config in vim
    "alias vv = vim ~/.vimrc",                        #Open vim config in vim
    "alias vnv = vim ~/.config/nvim/init.vim",        #Open neovim config in vim
    "alias vzsh = vim ~/.zshrc",                      #Open zsh config in vim
#NEOVIM ALIASES:
    #"alias vim = nvim",                               #Alias to replace vim with neovim
    "alias nvbash = nvim ~/.bashrc",                  #Open bash config in neovim
    "alias nvfish = nvim ~/.config/fish/config.fish", #Open fish config in neovim
    "alias nvv = nvim ~/.vimrc",                      #Open vim config in neovim
    "alias nvnv = nvim ~/.config/nvim/init.vim",      #Open neovim config in neovim
    "alias nvzsh = nvim ~/.zshrc",                    #Open zsh config in neovim
#DOOM-EMACS ALIASES:
    "alias doomhelp = ~/.emacs.d/bin/doom help",      #Show a list of available doom commands
    "alias doomsync = ~/.emacs.d/bin/doom sync",      #Sync config wiht Doom Emacs
    "alias doomupg = ~/.emacs.d/bin/doom upgrade",    #Update Doom Emacs & its package(s)
    "alias doomdoctor = ~/.emacs.d/bin/doom doctor",  #Diagnostic tool for Doom Emacs
    "alias doompurge = ~/.emacs.d/bin/doom purge",    #Delete old, orphaned package(s)
    "alias doominfo = ~/.emacs.d/bin/doom info",      #Output system info in markdown
    "alias doomver = ~/.emacs.d/bin/doom version",    #Show version info for Doom & Emacs

"def nudown [] {fetch https://api.github.com/repos/nushell/nushell/releases | get assets | select name download_count}",
    "def nuver [] {version | pivot key value}",
    ]
table_mode = "other" # basic, compact, compact_double, light, thin, with_love, rounded, reinforced, heavy, none, other
plugin_dirs = ["D:\\Src\\GitHub\\nu-plugin-lib\\samples\\Nu.Plugin.Len\\bin\\Debug\\netcoreapp3.1"]
pivot_mode = "auto" # auto, always, never
ctrlc_exit = false
complete_from_path = true
rm_always_trash = true
prompt = "build-string (ansi gb) (pwd) (ansi reset) '(' (ansi cb) (do -i { git rev-parse --abbrev-ref HEAD } | str trim ) (ansi reset) ')' (char newline) (ansi yb) (date format '%m/%d/%Y %I:%M:%S%.3f %p') (ansi reset) '> ' "

# for each of the options in the color_config section, you are able to set
# the color alone or with one of the following attributes.
# color, abbreviation
# green  g
# red    r
# blue   u
# black  b
# yellow y
# purple p
# cyan   c
# white  w
# attribute, abbreviation
# bold       b
# underline  u
# italic     i
# dimmed     d
# reverse    r
# abbreviated: green bold = gb, red underline = ru, blue dimmed = ud
# or verbose: green_bold, red_underline, blue_dimmed

[color_config]
primitive_int = "green"
primitive_decimal = "red"
primitive_filesize = "ur"
primitive_string = "pb"
primitive_line = "yellow"
primitive_columnpath = "cyan"
primitive_pattern = "white"
primitive_boolean = "green"
primitive_date = "ru"
primitive_duration = "blue"
primitive_range = "purple"
primitive_path = "yellow"
primitive_binary = "cyan"
separator_color = "purple"
header_align = "l" # left|l, right|r, center|c
header_color = "c" # green|g, red|r, blue|u, black|b, yellow|y, purple|p, cyan|c, white|w
header_bold = true
index_color = "rd"
leading_trailing_space_bg = "white"

[line_editor]
max_history_size = 100000
history_duplicates = "ignoreconsecutive" # alwaysadd,ignoreconsecutive
history_ignore_space = false
completion_type = "circular" # circular, list, fuzzy
completion_prompt_limit = 100
keyseq_timeout_ms = 500 # ms
edit_mode = "emacs" # vi, emacs
auto_add_history = true
bell_style = "audible" # audible, none, visible
color_mode = "enabled" # enabled, forced, disabled
tab_stop = 4

[textview]
term_width = "default" # "default" or a number
tab_width = 4
colored_output = true
true_color = true
header = true
line_numbers = true
grid = false
vcs_modification_markers = true
snip = true
wrapping_mode = "NoWrapping" # Character, NoWrapping
use_italics = true
paging_mode = "QuitIfOneScreen" # Always, QuitIfOneScreen, Never
pager = "less"
theme = "TwoDark"

# To add path and env do this
# > config set path $nu.path
# > config set env $nu.env
