#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore $SCRIPTPATH/down.jpg
fi

leftwm-command "UnloadTheme"

pkill compton
pkill picom
pkill polybar

